version: '3.9'
services:
  orb-slam3-ros-workspace:
    container_name: orb-slam3-ros-workspace
    build: .
    tty: true
    network_mode: "host"
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    devices:
      - /dev/video0:/dev/video0:mwr
